apiVersion: v1
kind: Service
metadata:
  name: {{ include "health-auto-export-server.fullname" . }}-mongo
  labels:
  {{- include "health-auto-export-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.type }}
  selector:
    io.kompose.service: mongo
    {{- include "health-auto-export-server.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
