apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "health-auto-export-server.fullname" . }}-grafana-claim0
  labels:
    io.kompose.service: grafana-claim0
  {{- include "health-auto-export-server.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.grafanaClaim0.storageRequest | quote }}
