apiVersion: v1
kind: Service
metadata:
  name: {{ include "health-auto-export-server.fullname" . }}-grafana
  labels:
    io.kompose.service: grafana
  {{- include "health-auto-export-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.type }}
  selector:
    io.kompose.service: grafana
    {{- include "health-auto-export-server.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
